### PR TITLE
Now Board is centered, and dynamically changing.

### PR DESCRIPTION
**Pull request by ilkukrisz**
.gitignore had been updated.
The required changes has been done. 
- The table is now contered to middle.
- Dynamically changing.

### CODE REVIEW

**Comment by ilkukrisz** [comment]
The changes sent in email had been done. As you said the drawing was perfect, only the place of it was the problem. I created a new class that extends the JPanel and now the paint method work perfectly. There is only one bottleneck left, when i click on the full window button de drawed rectanges remain the same sizes. I hope we can fix that very soon. Maybe now we can close the first issue.

**Comment by ldallos** [comment]
> There is only one bottleneck left, when i click on the full window button de drawed rectanges remain the same sizes. 

**Tip:**
The calculation of the scaleUnitWidth and scaleUnitHeight has to be placed in front of the myContainingJPanel.setSize method.

**Comment by ilkukrisz** [comment]
In the last commit, i have finished the required changes. Please check it. Thanks.

**Comment by ldallos** [comment]
The changes can be integrated to the Master branch.

**Pull request merged**
