### PR TITLE
Start screen and nice number printing added

### PR DESCRIPTION
**Pull request by ilkukrisz**
Hi! If you have time please test the code for any bugs that can occur. If the "image cant be loaded" , try with absolute path. Unfortunately i dont know the solution for that yet .. If everything is fine please merge it into master. Thanks.

### CODE REVIEW

**Comment by ldallos** [comment]
I got the image error during the start.
You can solve this problem with the following relative path: resources/background.png
That helped for me.

**Comment by ilkukrisz** [comment]
I thought that problem will rise up for you. In intellij you can mark a directory as "resources root", so when you want something it will start searching the file there. So I should change it, and then it is going to work on your laptop? Thanks for the fast response.

**Comment by ilkukrisz** [comment]
I thought that problem will rise up for you. In intellij you can mark a directory as "resources root", so when you want something it will start searching the file there. So I should change it, and then it is going to work on your laptop? Thanks for the fast response.

**Comment by ldallos** [comment]
You can also create a resource path in your project for example:
https://stackoverflow.com/questions/27934796/how-do-i-add-a-resources-folder-to-my-java-project-in-eclipse

In this case you can give only the name of the file with the following line:
private BufferedImage backgroundImage = ImageIO.read(new File(getClass().getClassLoader().getResource("background.png").getFile()));

**Comment by ldallos** [comment]
A third soultion:
You can get the current application full path with : new java.io.File( "." ).getCanonicalPath()

private BufferedImage backgroundImage = ImageIO.read(new File(new java.io.File( "." ).getCanonicalPath() + "/resources/background.png"));

**Pull request merged**
